version: '3'

services:
  wingman:
    image: firenaysh/wingman
    container_name: wingman
    ports:
      - '9999:9999'
    volumes: [./:/usr/src/app, node_modules:/usr/src/app/node_modules]
    command: npm run dev
    depends_on:
      - neo4j-db

  neo4j-db:
    image: neo4j:latest
    container_name: neo4j
    ports:
      - '7474:7474'
      - '7687:7687'
    environment: [NEO4J_AUTH=neo4j/secretgraph]
    volumes: [$HOME/neo4j/data:/data]

volumes:
  node_modules:
