name: build-tests

on:
  pull_request:
    branches: [main, dev]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node18.12.0-chrome106-ff106
      options: --user 1001
    # container:
    #   image: neo4j:latest
    services:
      neo4j:
        image: neo4j:latest
        ports:
          - '7474:7474'
          - '7687:7687'
        environment: [NEO4J_AUTH=neo4j/secretgraph]
        volumes: [$HOME/neo4j/data:/data]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          build: npm run build
          start: npm run dev
          browser: chrome
